---
title: "PCA"
author: "yongwen"
date: "2018年7月18日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# TFIDF 
```{r}
library(tm)
library(tmcn)
library(factoextra)
library(Matrix)

docs <- readLines("star_story.txt", encoding = "UTF-8")
docs <- gsub("\\[[0-9]+\\]", "", docs)
docs.corpus <- Corpus(VectorSource(docs))
docs.seg <- tm_map(docs.corpus, segmentCN)
docs.tdm <- TermDocumentMatrix(docs.seg, control = list())
inspect(docs.tdm)

#TFIDF counting
docs.tf <- apply(as.matrix(docs.tdm), 2, function(doc) {doc / sum(doc)})
idf.function <- function(word_doc) { log2( (length(word_doc)+1) / nnzero(word_doc) ) }
docs.idf <- apply(docs.tdm, 1, idf.function)
docs.tfidf <- docs.tf * docs.idf

```
# PCA
```{r}
docs.pca <- prcomp(docs.tfidf, scale = T)
```
# Drawing
```{r}
fviz_eig(docs.pca)
```

```{r}
fviz_pca_ind(docs.pca, geom.ind = c("point"), col.ind = "cos2")
```
```{r}
fviz_pca_var(docs.pca, col.var = "contrib")

```
```{r}
fviz_pca_biplot(docs.pca, geom.ind = "point")


```
```{r}
docs.eig <- get_eig(docs.pca)
docs.var <- get_pca_var(docs.pca)
docs.ind <- get_pca_ind(docs.pca)
```
# K-means
```{r}
ind.coord2 <- docs.ind$coord[, 1:2]
wss <- c()
for (i in 1:10) { wss[i] <- kmeans(ind.coord2, i)$tot.withinss }
plot(wss, type = "b")
```
```{r}
km <- kmeans(ind.coord2, 3)
plot(ind.coord2, col = km$cluster)
points(km$centers, col = 1:3, pch = 8, cex = 2)
```
